main: org.avaeriandev.titancore.TitanPlugin
name: ${project.name}
version: ${project.version}
author: AvaerianDev
description: ${project.description}

depend: [NBTAPI, EZBlocks, PlaceholderAPI, WorldGuard]

commands:
  commissary:
    description: Access the commissary panel
  warden:
    description: Access the warden panel
  ticket:
    aliases: [tickets, tix]
    description: Modify tickets for a user
  quest:
    description: Access the quest system
  fw:
    description: Play fireworks effect on player
  rifttool:
    aliases: [rifttools]
    description: Give a custom tool to a player
  enchanter:
    description: Access the enchanter panel
  speed:
    description: Toggles the speed effect for Titan players
  haste:
    description: Toggles the haste effect for Titan players
  dynamite:
    description: Debug command for dynamite
  magnet:
    description: Command to toggle magnet ability